services:
  db:
    image: mongo
    ports: 
      - "27019:27017" # host:container
  web:
    depends_on:
      - db
    build: .
    ports:
      - "3001:3000"
    environment:
      MONGO_DB_URI: 'mongodb://db:27017/prudential'

